spring:
  application:
    name: bookstore

  # ???? ?? - ??? local ??
  profiles:
    active: local

  # MySQL ?????? ??
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Minsung1234@
    driver-class-name: com.mysql.cj.jdbc.Driver

    # HikariCP
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA
  jpa:
    # Hibernate DDL
    hibernate:
      ddl-auto: update

    # SQL ?? ?? ?? (Logger ???, show-sql ??? ??? ??)
    # show-sql: true  # System.out ?? - ??

    # JPA
    properties:
      hibernate:
        # SQL
        format_sql: true
        # SQL
        use_sql_comments: true
        # Batch
        default_batch_fetch_size: 100
        use_jdbc_metadata_defaults: false

    database-platform: org.hibernate.dialect.MySQLDialect


  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    time-zone: Asia/Seoul

logging:
  level:
    root: INFO
    com.example.bookstore: DEBUG
    # org.hibernate.SQL: DEBUG  # 주석 처리하여 중복 방지
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always