spring:
  # H2 인메모리 데이터베이스 설정 (테스트용)
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # SQL 스크립트 실행 비활성화 (Hibernate가 자동으로 스키마 생성)
  sql:
    init:
      mode: never

  # H2 콘솔 활성화 (테스트 중 데이터 확인용)
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA 설정
  jpa:
    # 테스트 시작 시 스키마 재생성
    hibernate:
      ddl-auto: create-drop

    # SQL 쿼리 로깅 (단순하게 show-sql만 사용)
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        # 테스트에서는 배치 사이즈를 작게 설정
        default_batch_fetch_size: 10

    # H2 데이터베이스 플랫폼
    database-platform: org.hibernate.dialect.H2Dialect

  # Jackson 설정
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    time-zone: Asia/Seoul

# 테스트 로깅 설정 (운영보다 상세하게)
logging:
  level:
    root: INFO
    com.example.bookstore: DEBUG
    # Hibernate SQL 로깅 제거 (중복 방지)
    # org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    # TestContainers 로깅
    org.testcontainers: INFO
    com.github.dockerjava: WARN

# 테스트 서버 포트 (랜덤 포트 사용으로 충돌 방지)
server:
  port: 0